apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: default
data:
  prop1: hello
  prop2: world
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: test-container
      image: kadanli/livep:v0.1
      env:
        - name: envb
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: prop1
